--- #YAML:1.0
name:               Template-Plugin-Handy
version:            0.001
abstract:           handy vmethods for Template Toolkit
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:           0
    JSON::XS:             0
    Template::Plugin::VMethods:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
